apiVersion: v1
kind: Service
metadata:
  name: hello-kube-d
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kube-d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube-d
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: hello-kube-d
  template:
    metadata:
      labels:
        app: hello-kube-d
    spec:
      containers:
      - name: hello-kube-d
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hello-kube-config
          mountPath: /etc/config
      volumes:
      - name: hello-kube-config
        configMap:
          name: hello-kube-config
